import 'attendance_record.dart';
import 'gps_position.dart';
import 'operario.dart';

/// Port (hexagonal) — what the attendance feature needs from the outside world.
/// The data layer provides the implementation; the application layer depends
/// only on this interface.
abstract interface class AttendanceRepository {
  /// Returns the list of operarios scoped to the logged-in supervisor.
  /// Fetches the full list (no delta; ?since= is a STEP 2 optimisation).
  Future<List<Operario>> getOperarios();

  /// Posts a check-in for [operarioId] and returns the created [AttendanceRecord].
  ///
  /// [clientRef] is a uuid v4 generated by the caller. The backend is
  /// idempotent on [clientRef]: replaying it returns the same record (200).
  Future<AttendanceRecord> checkIn({
    required String operarioId,
    required String date,
    required DateTime capturedAt,
    required GpsPosition position,
    required String clientRef,
  });

  /// Uploads [signaturePngBytes] (PNG) as multipart/form-data to
  /// POST /asistencia/:id/signature. Must be called BEFORE [checkOut].
  Future<void> uploadSignature({
    required String attendanceId,
    required List<int> signaturePngBytes,
  });

  /// Posts a check-out for [attendanceId].
  /// The backend requires a signature to be uploaded first (422 otherwise).
  Future<AttendanceRecord> checkOut({
    required String attendanceId,
    required DateTime capturedAt,
    required GpsPosition position,
    required String checkOutClientRef,
  });

  /// Recovers a check-in record by its [clientRef] via
  /// `GET /asistencia?clientRef={clientRef}`.
  ///
  /// Returns the [AttendanceRecord] if found (the supervisor owns it), or
  /// `null` if not found (the check-in has not yet been processed server-side).
  ///
  /// Used by the offline queue replay to recover [serverAttendanceId] after a
  /// check-in POST whose response was lost (network drop after server commit).
  Future<AttendanceRecord?> recoverByClientRef(String clientRef);
}

/// Domain exception for attendance failures.
class AttendanceException implements Exception {
  const AttendanceException(this.message);

  final String message;

  @override
  String toString() => 'AttendanceException: $message';
}
