import 'attendance_record.dart';
import 'gps_position.dart';
import 'operario.dart';

/// Port (hexagonal) — what the attendance feature needs from the outside world.
/// The data layer provides the implementation; the application layer depends
/// only on this interface.
abstract interface class AttendanceRepository {
  /// Returns the list of operarios scoped to the logged-in supervisor.
  /// Fetches the full list (no delta; ?since= is a STEP 2 optimisation).
  Future<List<Operario>> getOperarios();

  /// Posts a check-in for [operarioId] and returns the created [AttendanceRecord].
  ///
  /// [clientRef] is a uuid v4 generated by the caller. The backend is
  /// idempotent on [clientRef]: replaying it returns the same record (200).
  /// [verification] is an optional audit label — AUDIT LABEL ONLY.
  Future<AttendanceRecord> checkIn({
    required String operarioId,
    required String date,
    required DateTime capturedAt,
    required GpsPosition position,
    required String clientRef,
    String? verification,
  });

  /// Uploads [photoBytes] (JPEG) as multipart/form-data to
  /// POST /asistencia/:id/photo?phase=[phase].
  ///
  /// [phase] must be 'checkin' (entry) or 'checkout' (exit).
  /// The entry photo must be uploaded before [checkOut] can succeed.
  Future<void> uploadPhoto({
    required String attendanceId,
    required List<int> photoBytes,
    required String phase,
  });

  /// Posts a check-out for [attendanceId].
  /// The backend requires a photo to be uploaded first (422 otherwise).
  /// [verification] is an optional audit label — AUDIT LABEL ONLY.
  Future<AttendanceRecord> checkOut({
    required String attendanceId,
    required DateTime capturedAt,
    required GpsPosition position,
    required String checkOutClientRef,
    String? verification,
  });

  /// Recovers a check-in record by its [clientRef] via
  /// `GET /asistencia?clientRef={clientRef}`.
  ///
  /// Returns the [AttendanceRecord] if found (the supervisor owns it), or
  /// `null` if not found (the check-in has not yet been processed server-side).
  ///
  /// Used by the offline queue replay to recover [serverAttendanceId] after a
  /// check-in POST whose response was lost (network drop after server commit).
  Future<AttendanceRecord?> recoverByClientRef(String clientRef);

  /// Returns today's attendance per operario for [date] (Colombia-local
  /// "YYYY-MM-DD"), scoped to the logged-in supervisor: `operarioId -> (id,
  /// completed)` where `completed` is true once BOTH check-in and check-out
  /// were registered.
  ///
  /// Drives the operario list:
  ///  - only a COMPLETED attendance (ingreso + salida) blocks a new fichaje;
  ///  - the [id] lets the supervisor attach an overtime novedad to it.
  /// The backend is the source of truth (unique [operarioId, date] constraint).
  Future<Map<String, ({String id, bool completed})>> todayAttendanceByOperario(
    String date,
  );
}

/// Domain exception for attendance failures.
///
/// [statusCode] carries the HTTP status code when the error originated from a
/// backend response — null for network errors where no response arrived.
/// The sync service uses statusCode to classify transient vs. terminal errors:
///   - null / >= 500          → TRANSIENT: leave pending for retry
///   - 409                    → recovery path (duplicate check-in)
///   - 4xx (422, 400, etc.)   → terminal: markFailed with [message]
class AttendanceException implements Exception {
  const AttendanceException(this.message, {this.statusCode});

  final String message;

  /// HTTP status code from the backend response, or null for network errors.
  final int? statusCode;

  @override
  String toString() => 'AttendanceException($statusCode): $message';
}
