import 'novedad.dart';

/// Port (hexagonal) — what the novedades feature needs from the outside world.
/// The data layer provides the implementation; application layer depends only
/// on this interface.
abstract interface class NovedadRepository {
  /// Creates a new overtime novedad for the completed attendance [attendanceId].
  ///
  /// [horasExtra] must be a positive numeric string ≤ 24 (e.g. "2.50").
  /// [clientRef] is a uuid v4 generated by the caller for idempotency.
  /// [motivo] is optional free text.
  ///
  /// Returns the created [Novedad] on 201 (or 200 for idempotent replay).
  /// Throws [NovedadException] with a Spanish message on 400/404/409.
  Future<Novedad> createNovedad({
    required String attendanceId,
    required String horasExtra,
    required String clientRef,
    String? motivo,
  });

  /// Returns all novedades scoped to the logged-in supervisor.
  ///
  /// TODO(offline): add ?since=ISO delta support once the offline queue is wired.
  Future<List<Novedad>> listNovedades();

  /// Returns a single novedad by [id].
  ///
  /// Throws [NovedadException] on 404.
  Future<Novedad> getNovedad(String id);

  /// Approves a pending novedad (PATCH /novedades/:id/approve).
  ///
  /// Throws [NovedadAlreadyDecidedException] on 409 (already approved/rejected).
  /// Throws [NovedadException] on 404 or other errors.
  Future<void> approveNovedad(String id);

  /// Rejects a pending novedad (PATCH /novedades/:id/reject).
  ///
  /// Throws [NovedadAlreadyDecidedException] on 409 (already approved/rejected).
  /// Throws [NovedadException] on 404 or other errors.
  Future<void> rejectNovedad(String id);
}

/// Domain exception for novedad failures. Always carries a Spanish message
/// suitable for display in the UI.
class NovedadException implements Exception {
  const NovedadException(this.message);

  final String message;

  @override
  String toString() => 'NovedadException: $message';
}

/// Thrown when the backend returns 409 — the novedad was already decided.
/// Carries a Spanish message suitable for display.
class NovedadAlreadyDecidedException implements Exception {
  const NovedadAlreadyDecidedException(this.message);

  final String message;

  @override
  String toString() => 'NovedadAlreadyDecidedException: $message';
}
